name: Build Selfhost Image

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Select distribution to build'
        type: choice
        default: hml
        options:
          - canary
          - beta
          - stable
          - hml
          - prd

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'

jobs:
  build-image:
    name: Build Image
    uses: ./.github/workflows/build-server-image.yml
    secrets: inherit
    with:
      flavor: ${{ github.event.inputs.flavor }}
